name:                telescope
version:             0.1.2
synopsis:            Astronomical Observations (FITS, ASDF, WCS, etc)
description:         Work with astronomical observations from modern telescopes
homepage:            https://github.com/dkistdc/telescope.hs
license:             BSD3
author:              Sean Hess
maintainer:          Sean Hess <shess@nso.edu>
copyright:           (c) 2024 Sean Hess
category:            Science, Astronomy
extra-source-files:
  - README.md
  - src/checksum.c
  - src/checksum.h

language: GHC2021

ghc-options:
  - -Wall

default-extensions:
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DerivingStrategies
  - DuplicateRecordFields
  - LambdaCase
  - NoFieldSelectors
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - StrictData
  - TypeApplications
  - TypeFamilies

dependencies:
  - base >= 4.7 && < 5
  - binary >= 0.8.9 && <0.9
  - bytestring >= 0.11 && <0.12
  - exceptions >= 0.10 && <0.11
  - fits-parse >= 0.4.2 && < 0.5
  - massiv >= 1.0 && < 1.1
  - megaparsec >= 9.6 && <9.7
  - text >= 2.0 && <3
  - effectful >= 2.3 && <3

library:
  source-dirs: src
  c-sources:
    - src/checksum.c


tests:
  spec:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - telescope
    - binary
    - containers

    # envparse 0.5 gives error in sydtest
    - sydtest >= 0.15
    - envparse >= 0.4 && <= 0.5



